username = input("Введите имя пользователя: ")
title1 = input("Введите 1-ый заголовок заметки: ")
title2 = input("Введите 2-ой заголовок заметки: ")
title3 = input("Введите 3-ий заголовок заметки: ")
title_list = [title1, title2, title3]
content = input("Введите небольшое описание заметки: ")
status = input("Введите статус заметки (Например: К исполнению/В работе/Выполнена): ")
created_date = input("Введите дату создания заметки в формате DD-MM-YYYY: ")
issue_date = input("Введите дату истечения заметки (дедлайн) в формате DD-MM-YYYY: ")

print("Имя пользователя: ", username)
print("Заголовоки заметки: ", title_list)
print("Описание заметки: ", content)
print("Статус заметки: ", status.lower())
print("Дата создания заметки: ", created_date[:5])
print("Дата истечения заметки (дедлайн): ", issue_date[:5])